# Generated by Django 4.2.6 on 2023-12-05 13:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(blank=True, max_length=15, verbose_name='Ref number')),
                ('inv_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Invoice date')),
                ('observations', models.CharField(blank=True, max_length=4000)),
                ('created_by', models.CharField(blank=True, max_length=15, null=True, verbose_name='Created by')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid date')),
                ('tax', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=5, verbose_name='Tax')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=5, verbose_name='Discount')),
                ('total', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Total')),
                ('total_paid', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=6, null=True, verbose_name='Paid')),
                ('to_paid', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=6, null=True, verbose_name='To Paid')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('is_cancelled', models.BooleanField(default=False, help_text='Deleted invoices', verbose_name='Cancelled')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('updated_by', models.CharField(blank=True, max_length=15, null=True, verbose_name='Updated by')),
            ],
            options={
                'verbose_name_plural': 'Purchase_invoice',
                'db_table': 'Purchase_invoice',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Supplier')),
                ('ref_no', models.CharField(blank=True, max_length=255, verbose_name='Ref number')),
                ('address', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=255, verbose_name='Contact number')),
                ('email', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=15, null=True, verbose_name='Created by')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Purchase_invoice_dtl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveBigIntegerField(default='1', verbose_name='Quantity(unit)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='suppliers.purchase_invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invoice_items', to='store.product')),
            ],
            options={
                'verbose_name_plural': 'Purchase_invoice_dlt',
                'db_table': 'Purchase_invoice_dlt',
            },
        ),
        migrations.AddField(
            model_name='purchase_invoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier'),
        ),
    ]
